# Generated by Django 4.2 on 2024-06-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='name',
            new_name='nome',
        ),
    ]
