# Generated by Django 5.0.6 on 2024-07-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_name_local_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embalagem',
            old_name='unidade',
            new_name='sigla',
        ),
    ]
